from typing import Iterator, overload
from collections.abc import Iterable
from .vector3 import Vector3

class Quaternion:
    x: float
    y: float
    z: float
    w: float

    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __neg__(self) -> Quaternion: ...
    @overload
    def __mul__(self, other: Quaternion) -> Quaternion: ...
    @overload
    def __mul__(self, other: Vector3) -> Vector3: ...

    @staticmethod
    def identity() -> Quaternion: ...
    @staticmethod
    def from_euler(degX: float, degY: float, degZ: float, order: str = "ZXY") -> Quaternion: ...
    @staticmethod
    def from_iterable(iterable: Iterable) -> Quaternion: ...

    def dot(self, other: Quaternion) -> float: ...
    def normalize(self) -> None: ...
    def normalized(self) -> Quaternion: ...
    def inverse(self) -> Quaternion: ...
    def slerp(self, other: Quaternion, t: float) -> Vector3: ...
    def to_list(self) -> list[float]: ...
    def to_euler(self, order: str = "ZXY") -> Vector3: ...