from .transform import Transform
from .vector3 import Vector3
from .quaternion import Quaternion

def print_tree(depth: int, transform: Transform) -> None: ...

class SceneGraph:
    root_name: str

    def __init__(self) -> None: ...
    def __getitem__(self, key: str) -> Transform: ...
    def __contains__(self, item: object) -> bool: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...

    @property
    def root(self) -> Transform: ...

    def apply_transform(self, transform_name: str, parent_name: str, local_position: Vector3, local_rotation: Quaternion) -> None: ...
    def remove(self, transform_name: str) -> None: ...
    def print_graph(self) -> None: ...
