from typing import Iterator, overload
from .vector3 import Vector3
from .quaternion import Quaternion

class Transform:
    name: str
    local_position: Vector3
    local_rotation: Quaternion
    position: Vector3
    rotation: Quaternion
    parent: Transform | None

    def __init__(self, pos: Vector3, rot: Quaternion, name: str = "") -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @overload
    def __mul__(self, other: Transform) -> Transform: ...
    @overload
    def __mul__(self, other: Vector3) -> Vector3: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Transform]: ...
    def __getitem__(self, items: int | slice) -> Transform | list[Transform]: ...
    def __setitem__(self, key: int, newvalue: Transform) -> None: ...

    @property
    def x_dir(self) -> Vector3: ...
    @property
    def y_dir(self) -> Vector3: ...
    @property
    def z_dir(self) -> Vector3: ...

    def set_local_pos_rot(self, local_position: Vector3, local_rotation: Quaternion) -> None: ...
    def set_local_pos_rot_parent(self, local_position: Vector3, local_rotation: Quaternion, parent: Transform) -> None: ...
    def inverse(self) -> Transform: ...
    def rotate(self, rotation: Quaternion) -> None: ...
    def translate(self, translation: Vector3) -> None: ...
    def add_child(self, transform: Transform) -> None: ...
    def world_to_local(self, world_pos: Vector3) -> Vector3: ...
    def local_to_world(self, local_pos: Vector3) -> Vector3: ...
