from typing import Iterator
from collections.abc import Iterable

class Vector3:
    x: float
    y: float
    z: float

    def __init__(self, x: float, y: float, z: float) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __neg__(self) -> Vector3: ...
    def __add__(self, other: Vector3 | float | int) -> Vector3: ...
    def __sub__(self, other: Vector3 | float | int) -> Vector3: ...
    def __mul__(self, other: Vector3 | float | int) -> Vector3: ...
    def __truediv__(self, other: Vector3 | float | int) -> Vector3: ...
    def __rmul__(self, other: Vector3 | float | int) -> Vector3: ...
    
    @property
    def xxx(self) -> Vector3: ...
    @property
    def xxy(self) -> Vector3: ...
    @property
    def xxz(self) -> Vector3: ...
    @property
    def xyx(self) -> Vector3: ...
    @property
    def xyy(self) -> Vector3: ...
    @property
    def xyz(self) -> Vector3: ...
    @property
    def xzx(self) -> Vector3: ...
    @property
    def xzy(self) -> Vector3: ...
    @property
    def xzz(self) -> Vector3: ...
    @property
    def yxx(self) -> Vector3: ...
    @property
    def yxy(self) -> Vector3: ...
    @property
    def yxz(self) -> Vector3: ...
    @property
    def yyx(self) -> Vector3: ...
    @property
    def yyy(self) -> Vector3: ...
    @property
    def yyz(self) -> Vector3: ...
    @property
    def yzx(self) -> Vector3: ...
    @property
    def yzy(self) -> Vector3: ...
    @property
    def yzz(self) -> Vector3: ...
    @property
    def zxx(self) -> Vector3: ...
    @property
    def zxy(self) -> Vector3: ...
    @property
    def zxz(self) -> Vector3: ...
    @property
    def zyx(self) -> Vector3: ...
    @property
    def zyy(self) -> Vector3: ...
    @property
    def zyz(self) -> Vector3: ...
    @property
    def zzx(self) -> Vector3: ...
    @property
    def zzy(self) -> Vector3: ...
    @property
    def zzz(self) -> Vector3: ...

    @staticmethod
    def zero() -> Vector3: ...
    @staticmethod
    def one() -> Vector3: ...
    @staticmethod
    def x_one() -> Vector3: ...
    @staticmethod
    def y_one() -> Vector3: ...
    @staticmethod
    def z_one() -> Vector3: ...
    @staticmethod
    def from_iterable(iterable: Iterable) -> Vector3: ...

    def dot(self, other: Vector3) -> float: ...
    def magnitude(self) -> float: ...
    def normalize(self) -> None: ...
    def normalized(self) -> Vector3: ...
    def cross(self, other: Vector3) -> Vector3: ...
    def inverse(self) -> Vector3: ...
    def lerp(self, other: Vector3, t: float) -> Vector3: ...
    def distance(self, other: Vector3) -> float: ...
    def to_list(self) -> list[float]: ...